# Este Pipeline irá instalar dependências Python, executar lint (PEP-8) com as três últimas versões Python 3.9, 3.8 e 3.7

name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Instalando dependências
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Link com Flake8
      run: |
        # quebra CI se erros de sintaxe forem encontrados
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # mostra aviso dos erros com tamanho máximo da linha de 127 caracterers, default do editor github
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Testes pytest
      run: |
        pytest
    - name: Deploy Server
      with:
        ref: 'refs/heads/release/snapshot'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  